DATA:
  data_name: s3dis_w_openset
  data_root: /data1/ljn/point-transformer/data/stanford_indoor3d/
  test_area: 5
  classes: 13
  fea_dim: 6
  voxel_size: 0.04
  voxel_max: 80000
  loop: 30
  open_label: [5,9]

TRAIN:
  arch: pointtransformer_seg_repro
  freeze_encoder: True
  freeze_decoder: False
  lamda_dummy: 0.1
  lamda_var: 0.01
  lamda_sim: 1
  use_xyz: True
  sync_bn: False
  ignore_label: 0
  train_gpu: [0,1]
  mini_open_num: 1000
  in_dim: 32
  out_dim: 32
  workers: 8  # data loader workers
  batch_size: 16 # batch size for training 8 16
  batch_size_val: 4  # batch size for validation during training, memory and speed trade-off
  base_lr: 0.001
  beta1: 0.9
  beta2: 0.999
  G_lr: 0.0002
  D_lr: 0.0001
  weight_adversarialLoss: 0.2
  epochs: 30
  start_epoch: 0
  step_epoch: 10
  multiplier: 0.1
  momentum: 0.9
  weight_decay: 0.0001
  drop_rate: 0.5
  manual_seed: 7777
  print_freq: 10
  save_freq: 1
  save_path:
  weight: True # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1
Distributed:
  dist_url: tcp://localhost:8888
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

TEST:
  test_list: dataset/s3dis/list/val5.txt
  test_list_full: dataset/s3dis/list/val5_full.txt
  split: val  # split in [train, val and test]
  test_gpu: [3]
  test_workers: 4
  batch_size_test: 2
  model_path: /data1/ljn/point-transformer/exp/s3dis/pointtransformer_trans/model/model_best.pth #/data1/ljn/point-transformer/exp/s3dis/pointtransformer_trans/model/model_best_固定解码器
  generator_path: /data1/ljn/point-transformer/exp/s3dis/pointtransformer_trans/model/GNet_best.pth
  discriminator_path: /data1/ljn/point-transformer/exp/s3dis/pointtransformer_trans/model/classifier_best.pth
  save_folder: /data1/ljn/point-transformer/exp/s3dis/pointtransformer_proto_with_gan/result
  names_path: /data1/ljn/point-transformer/data/s3dis/s3dis_names.txt
